### ISSUE TITLE
没有效果

### ISSUE THREAD

**Issue by niaiai** [mrgeneralgoo/typecho-markdown#1]
我下载激活之后 没有达到你博客上面的效果 需要修改什么么

**Comment by mrgeneralgoo** [comment]
有具体的无效例子吗？

使用只需要**单行**使用 `[TOC]` 语法即可。

目录的生成依赖 h1,h2...,h6 这样的多层级段落格式

**Comment by niaiai** [comment]
编辑时预览有有效果 代码也有着色 
浏览正文是 就没有预览时那么完美
有什么办法 让正文也那么好看吗

**Comment by mrgeneralgoo** [comment]
样式这个，不同的模板，样式都不一样，不好统一。

生成的目录使用的元素就是 `<ul><li>` ，对正文里面这两个元素加上合适的样式即可。

**Comment by niaiai** [comment]
谢谢 大佬
有好看的样式 推荐一下吗

**Comment by hiCasper** [comment]
你好，我启用后没有效果，请问这个插件是如何实现替换的，需要额外调用吗？主题也没有自带解析，用的都是系统的解析。

**Comment by mrgeneralgoo** [comment]
@hiCasper 

使用只需要**单行**使用 `[TOC]` 语法即可。

目录的生成依赖 h1,h2...,h6 这样的多层级段落格式
对应到 markdown 语法就是 `#`  `##` ...
