### ISSUE TITLE
mathjax解析不全

### ISSUE THREAD

**Issue by slen99** [mrgeneralgoo/typecho-markdown#12]
我在启用插件之后，只有两个$$之间的公式解析了，两个$之间的公式却没有解析，这是为什么呢？

**Comment by mrgeneralgoo** [comment]
能提供更详细的信息吗？ 

 https://www.chengxiaobai.cn/php/markdown-parser-library.html 
这个例子里面分别有 `$` 和 `$$` 的效果。

`$f(x,y,z) = 3y^2z \left( 3+\frac{7x+5}{1+y^2} \right)$`

```
$$ F^{HLLC}=\left\{
\begin{array}{rcl}
F_L       &      & {0      <      S_L}\\
F^*_L     &      & {S_L \leq 0 < S_M}\\
F^*_R     &      & {S_M \leq 0 < S_R}\\
F_R       &      & {S_R \leq 0}
\end{array} \right. $$
```
