### ISSUE TITLE
配合DPlayer-Typecho插件使用时，把url资源解析为null

### ISSUE THREAD

**Issue by shafishcn** [mrgeneralgoo/typecho-markdown#14]
![issue](https://cdn.shafish.cn/imgs/issue.png)

- 开启MarkdownParse解析后，把[dplayer url="https://cdn.shafish.cn/video/april.mp4" /] 里的url资源解析没了；

- 关闭MarkdownParse插件后，[DPlayer](https://github.com/MoePlayer/DPlayer-Typecho)可以正常工作

https://cdn.shafish.cn/imgs/issue.png

有点手残，不知道怎么解决，把插件升级到最新版后 问题还存在。希望作者有时间看看，笔芯!

**Comment by mrgeneralgoo** [comment]
> [dplayer url="https://cdn.shafish.cn/video/april.mp4" /] 

这段文字没有任何特殊之处，所以会被当作普通 markdown 文本被解析，解析结果如下：

`[dplayer url="<a href="https://cdn.shafish.cn/video/april.mp4">https://cdn.shafish.cn/video/april.mp4</a>" /]`

禁用 MarkdownParse 之后，默认的解析器是没有完整识别里面的 URL 的，所以解析的结果如下：

`[dplayer url="https://cdn.shafish.cn/video/april.mp4" /] `

那问题就很明显了：DPlayer 无法识别里面 HTML 的 `<a>` 标签里面的 URL。本来想去提个 PR 增强下其识别能力，我去看了下 [DPlayer](https://github.com/MoePlayer/DPlayer-Typecho) 插件的源码，发现是从  wordpress copy 过来的代码，作罢。

那就从写法上规避吧：`<div>[dplayer url="https://cdn.shafish.cn/video/april.mp4" /]</div>`

按照 markdown 的规范来写，MarkdownParse 会把它当作 HTML 来对待，不去解析里面的东西，就能正常被识别了。

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/13347471/81471267-88ce8280-9222-11ea-8115-82a1d7616d5b.png">
