### ISSUE TITLE
能够启用TOC但是无法支持MathJax语法

### ISSUE THREAD

**Issue by Karl-Han** [mrgeneralgoo/typecho-markdown#16]
按照安装的步骤，安装并启用了插件，同时也通过启用和禁用解析TOC的语法来确认插件能够正常运行。

尝试过安装release中的v1.2.3以及master版本的。

但是现在无法显示MathJax的行内以及多行的数学公式语法，具体的例子来自于：https://www.chengxiaobai.cn/record/markdown-concise-grammar-manual.html

**Comment by mrgeneralgoo** [comment]
请使用 1.3.0 版本
