### ISSUE TITLE
不支持注脚语法了

### ISSUE THREAD

**Issue by ihewro** [mrgeneralgoo/typecho-markdown#17]
1.1.0中 是支持的，但是注脚的序号又问题不是从1开始的
1.3.0中 不支持了，直接变成了url的语法了

具体复现可以测试https://www.zybuluo.com/mdeditor?url=https://www.zybuluo.com/static/editor/md-help.markdown#fnref:footnote  作业帮文本里面的注脚

**Comment by mrgeneralgoo** [comment]
请使用 1.4.0 版本  https://github.com/mrgeneralgoo/typecho-markdown/releases
