### ISSUE TITLE
无法正确的进行解析

### ISSUE THREAD

**Issue by CornWorld** [mrgeneralgoo/typecho-markdown#18]
[博客测试页面传送门](https://www.had.ink/test/)
[博客地址](https://www.had.ink/)

启用后发现啥都没变（Todolist没渲染 mermaid没渲染 下标没渲染），求解答

Typecho版本：1.1 (17.10.30)
主题：DreamCat（自己魔改了一下）

![插件已经启用](https://user-images.githubusercontent.com/43746030/99521888-f2003100-29cf-11eb-9497-8b95ba0ea3e0.png)
![插件设置](https://user-images.githubusercontent.com/43746030/99522237-5a4f1280-29d0-11eb-9b4d-c8fd9c64cc74.png)
![插件列表](https://user-images.githubusercontent.com/43746030/99522408-8f5b6500-29d0-11eb-911f-632a058589f6.png)

**Comment by mrgeneralgoo** [comment]
你的 blog 已经 502 了

**Comment by CornWorld** [comment]
emm 我这边并没有502，应该是配cdn的时候源站那边没整好 qqqaq
如果一直502的话，可以试一下[这个链接](https://had.ink/) 或者[反代镜像](http://ink.had.xin:50/)

**Comment by mrgeneralgoo** [comment]
看起来渲染并没有生效，是否有其他渲染插件？

并且流程图的写法好像也和本插件约定的不一样。

<img width="780" alt="image" src="https://user-images.githubusercontent.com/13347471/103736981-46b54500-502c-11eb-916f-e9cfa41bea44.png">

你可以参考：https://www.chengxiaobai.cn/record/markdown-concise-grammar-manual.html#Sequence+Diagram

**Comment by CornWorld** [comment]
粘贴上面的代码后依旧无法使用，显然肯定不是语法的问题
经过排查好像并没有发现有其他的渲染插件，如果勉强说是渲染的话，生成目录树的插件可能会参与一部分的渲染？
正在进行排查，晚一点会继续反应情况

**Comment by CornWorld** [comment]
能否提供一下其他联系方式？
请发至 cw@had.ink 谢谢
