### ISSUE TITLE
加上 [TOC] 后乱码

### ISSUE THREAD

**Issue by jpsia** [mrgeneralgoo/typecho-markdown#2]
加上 [TOC] 乱码, 去掉就正常.

**Comment by mrgeneralgoo** [comment]
首先检查一下你的文本编码格式，这点可以通过浏览器编码选择来判定。

如果乱码问题依旧，请描述下乱码类型。

但是如果是`&#23450`这样的乱码，其实是numeric character reference（NCR），并不是所谓的乱码。

**Comment by mrgeneralgoo** [comment]
乱码隐患已经在1.1.0版本彻底解决
