### ISSUE TITLE
关于MarkdownParse的一个小问题

### ISSUE THREAD

**Issue by yuuuuu422** [mrgeneralgoo/typecho-markdown#20]
这是我的网站 [Theoyu's Blog](http://theoyu.top/index.php/archives/23/)
不知道为什么 TOC生成的目录点击不能进行跳转
但是可以右键打开一个新的页面 在新的页面可以跳转

**Comment by CornWorld** [comment]
在我这里是可以正常运作的（或许你已经解决了这个问题？）

------------------
环境
- 浏览器：Chrome 87.0.4280.88（正式版本） （32 位）
- 系统：Windows7 旗舰版（Service Pack 1）

**Comment by mrgeneralgoo** [comment]
因为你的主题自带了目录功能，它通过 JS 实现，并且会侵入修改文章中原来的 id 锚点，导致服务端生成的 id 锚点无法跳转定位。

<img width="258" alt="image" src="https://user-images.githubusercontent.com/13347471/103737445-3ce01180-502d-11eb-8f54-c92b2b663e2f.png">

服务端生成的目录在新页面能生效，是因为主题自带的目录功能有缺陷：第一次并没有渲染出来 or 渲染太慢。等它渲染出来就会修改文章中原来的 id 锚点，导致服务端生成的目录无法跳转定位。
