### ISSUE TITLE
后台预览界面解析器没有跟随修改

### ISSUE THREAD

**Issue by MorningP** [mrgeneralgoo/typecho-markdown#21]
hi，我安装了这个插件，但是我注意到后台编辑时，预览界面所展现的效果与我发布文章后实际呈现的效果并不一样。例如我再编辑时是这样的效果（请注意图片前后文字的缩进）
<img width="960" alt="1" src="https://user-images.githubusercontent.com/61961964/118443806-4e49d080-b727-11eb-8555-933d56ec2514.png">
但是展现在网页中的效果 htps://blog.morningp.name/index.php/%E7%AC%94%E8%AE%B0/45.html 是这样的。
我想这是由于后台预览界面的解析器没有跟随修改。请问可以增加这样的修改吗？

**Comment by mrgeneralgoo** [comment]
我看了下，这个预览功能本身的渲染还是通过本插件来的，就是排版样式上是 Typecho 自带的样式布局有点问题（真实的文章页面和编辑器预览展现上就是有差异），这个不在这个项目范畴内了，目前有两种方式可以实现稳定的预览效果：
1. 使用 Typecho 的「预览文章」功能
2. 使用「所见即所得」的 Markdown 编辑器写文章后发布到 Typecho 上（我使用的是 Typora）
