### ISSUE TITLE
不能正常安装

### ISSUE THREAD

**Issue by bily-goat** [mrgeneralgoo/typecho-markdown#23]
按照您说的解压到了正确位置，只是启用的时候出现了bug
`Parse error: syntax error, unexpected '=' in /www/wwwroot/www.我的网站根目录.com/usr/plugins/MarkdownParse/Parsedown.php on line 532`
我的php版本 php5.6
服务器 centos7
typecho版本 1.1 (17.10.30)
typecho-markdown版本 最新

**Comment by bily-goat** [comment]
`Parse error: syntax error, unexpected '=' in /www/wwwroot/www.yeschanblog.com/usr/plugins/MarkdownParse/Parsedown.php on line 532`
我的php版本 php5.6
服务器 centos7
typecho版本 1.1.6
typecho-markdown版本 最新

**Comment by mrgeneralgoo** [comment]
感谢反馈，已经处理，使用了一个 PHP 7.1 语法导致了不兼容。
