### ISSUE TITLE
作者大大，能否加入上标和下标的解析

### ISSUE THREAD

**Issue by Yugu-FishBone** [mrgeneralgoo/typecho-markdown#24]
将下标:
```
H~2~O 解析成 H<sub>2</sub>O
```
H<sub>2</sub>O

将 上标：
```
X^2^ 解析成 X<sup>2</sup>
```
X<sup>2</sup>

**Comment by mrgeneralgoo** [comment]
涉及上下标的需求似乎用 MathJax 公式来实现兼容性、拓展性会更好点（本插件支持 MathJax 哟 😋）？

上标：`$X^2$` 
下标：`$H_2O$`

<img width="692" alt="image" src="https://user-images.githubusercontent.com/13347471/121858156-e3d97f80-cd28-11eb-91dc-25721af69711.png">
