### ISSUE TITLE
加了 [TOC] 好像没有作用

### ISSUE THREAD

**Issue by LikeJson** [mrgeneralgoo/typecho-markdown#27]
在文章头部加了 [TOC]直接被原样输出了

![image](https://user-images.githubusercontent.com/85022954/130170047-cde283e7-6111-40bf-9e90-ae659b163ec7.png)
文章链接

https://jkkoi.top/archives/26.page

部分后台原文
```
[TOC]
.....
# flag1
文件名，打开就能看到
![2021-08-18T03:48:09.png][2]

# flag2 & flag3 & flag4
CRC 异常，跑程序爆破宽高
![2021-08-18T04:19:29.png][3]

打开后图片显示不完全
......
```

**Comment by mrgeneralgoo** [comment]
> 肯定开了呀😂😂

emmmm  还开启了其他 markdown 插件吗？

我们俩环境相同，如果没有其他 markdown 插件并且你的内容编写没问题的话，你再单独试试如下写法看能否生效。
```markdown
[TOC]

# flag1
文件名，打开就能看到
![2021-08-18T03:48:09.png][2]

# flag2 & flag3 & flag4
CRC 异常，跑程序爆破宽高
![2021-08-18T04:19:29.png][3]
```

**Comment by LikeJson** [comment]
![image](https://user-images.githubusercontent.com/85022954/131221887-7a0f3dd8-9d5e-4a8b-ab27-5a4aba4bde1e.png)

没有 markdown 相关插件

**Comment by mrgeneralgoo** [comment]
> ![image](https://user-images.githubusercontent.com/85022954/131221887-7a0f3dd8-9d5e-4a8b-ab27-5a4aba4bde1e.png)
> 
> 没有 markdown 相关插件

单发一篇测试文章，试试吧，内容就是上面我贴的内容

**Comment by LikeJson** [comment]
破案
`[TOC]` 后面必须空一行
```
[TOC]

xxxxxxxx
```
