### ISSUE TITLE
升级typecho最新开发版报错

### ISSUE THREAD

**Issue by smallmocha** [mrgeneralgoo/typecho-markdown#28]
Return value of Typecho\Widget\Helper\Form\Element\Radio::input() must be an instance of Typecho\Widget\Helper\Layout, boolean returned

**Comment by mrgeneralgoo** [comment]
I'll test it in 2.0

**Comment by smallmocha** [comment]
> I'll test it in 2.0

说错了，没有2.0版本，就是github最新的开发版啦

**Comment by mrgeneralgoo** [comment]
> > I'll test it in 2.0
> 
> 说错了，没有2.0版本，就是github最新的开发版啦

😂，好的，我看了下最新的提交记录，Typecho 可能要发新版本了，改动比较大，大家反馈的问题也不少，稍等相对稳定点再兼容。

**Comment by smallmocha** [comment]
> > > I'll test it in 2.0
> > 
> > 
> > 说错了，没有2.0版本，就是github最新的开发版啦
> 
> 😂，好的，我看了下最新的提交记录，Typecho 可能要发新版本了，改动比较大，大家反馈的问题也不少，稍等相对稳定点再兼容。

已联系typecho作者修复，兼容了
