### ISSUE TITLE
启动后主页无法浏览

### ISSUE THREAD

**Issue by CmmmmmmLau** [mrgeneralgoo/typecho-markdown#29]
直接报错`Call to undefined function mb_strlen()`
似乎是主题的问题?
PHP 7.3 + SQLite3
主题是icarus
https://github.com/keroliang/typecho-theme-icarus

**Comment by mrgeneralgoo** [comment]
`mb_strlen`  依赖 PHP mbstring 拓展，该拓展也是 Typecho 环境的基础依赖。
