### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by Ablegang** [mrgeneralgoo/typecho-markdown#3]
为了阅读方便，可以考虑把toc的列表生成在左右两边。

**Comment by mrgeneralgoo** [comment]
emmmmm...

这个是需要 JavaScript 支持的，理论上不同的博客主题，可能最终呈现的效果都不太一样，也无法做到通用适配。

所以目录结构在 html 编码上并没有添加任何样式，但是其实可以后期通过自定义 JavaScript 来实现不同效果的，这个因人而异吧。
