### ISSUE TITLE
兼容PHP8：修复ParsedownExtra.php文件报错

### ISSUE THREAD

**Issue by mulingyuer** [mrgeneralgoo/typecho-markdown#39]
目前发现了ParsedownExtra.php文件中使用了`self`语法，这个会在8.0抛出错误，解决办法就是通过闭包函数来修复这个问题，我们找到`uasort($this->DefinitionData['Footnote'], 'self::sortFootnotes');`这段代码，修改为如下：

```php
uasort($this->DefinitionData['Footnote'], function ($a, $b) {
    return $this->sortFootnotes($a, $b);
});
```

**Comment by mrgeneralgoo** [comment]
感谢的你反馈，本项目的依赖库长时间没更新，我得看下是否有更合适的解析器。

**Comment by mulingyuer** [comment]
坐等作者大大更新了☺️
