### ISSUE TITLE
TOC 标签不支持自定义

### ISSUE THREAD

**Issue by pdarinrzhouc** [mrgeneralgoo/typecho-markdown#40]
我看别人说 github 不支持toc,但是支持自己写的目录:

```
- [提示文字](#标题)
```

直接使用 TOC 会解析所有标题,但是我希望不解析主题和目录这两个二级标题，而 github 的这种目录插件好像不支持。

用 a 标签的话 md 的编辑界面看起来又很丑。

所以不知道该怎么操作了，请问作者还在维护吗？

**Comment by mrgeneralgoo** [comment]
还在维护，本项目的依赖库长时间没更新，我得看下是否有更合适的解析器。


不过你说的功能似乎有另外的解法：支持目录层级限制，以及排除某些目录？

**Comment by pdarinrzhouc** [comment]
明白了，确实可以通过限制一些层级的输出来达到相同的目的。
