### ISSUE TITLE
我安装后显示“即插即用”，没有配置选项

### ISSUE THREAD

**Issue by anyunpu** [mrgeneralgoo/typecho-markdown#53]
我安装后显示“即插即用”，没有配置选项，mermaid代码也没生效
![image](https://github.com/mrgeneralgoo/typecho-markdown/assets/44797254/bdcaca13-619e-41f9-a97e-df01cea2f5bc)
![image](https://github.com/mrgeneralgoo/typecho-markdown/assets/44797254/3bb2d150-703c-49a6-9a39-82fa4d413eee)

环境：
typecho：1.2
PHP：8.2.6

**Comment by mrgeneralgoo** [comment]
🤔️ 啊？ 难道是新版本的原因，我抽空看看

**Comment by anyunpu** [comment]
我昨晚升级到最新版 1.3，然后它又可以了

**Comment by anyunpu** [comment]
大佬能配套一个编辑器不

**Comment by mrgeneralgoo** [comment]
好吧，我一般是用最新的开发版（master 分支最新 commit）来做开发测试，然后再用稳定版验证，如果能复现可以提供下版本信息或者 commit hash

**Comment by anyunpu** [comment]
是的，后台编辑器

**Comment by duskdusts** [comment]
![图片](https://github.com/mrgeneralgoo/typecho-markdown/assets/60814886/bf7e4e53-9f05-41fa-90c2-0170985f033f)
我的也是，就1.2.1版本

**Comment by mrgeneralgoo** [comment]
我抽空看看 🤦

**Comment by anyunpu** [comment]
> ![图片](https://private-user-images.githubusercontent.com/60814886/332257507-bf7e4e53-9f05-41fa-90c2-0170985f033f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDU0ODMsIm5iZiI6MTcxNjM0NTE4MywicGF0aCI6Ii82MDgxNDg4Ni8zMzIyNTc1MDctYmY3ZTRlNTMtOWYwNS00MWZhLTkwYzItMDE3MDk4NWYwMzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAyMzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZjIzNjQ1NGUyYjhlOWE5ZGExNmU2NDRkYWEzNDgzNmNiNzgyMWNlZTI0N2ZlZjIwYmUwNzkzOTcyYjY2MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.85ITWadLm1IsTtZlUZLN_t0LTV3jKd_MsWDk3qfdcVs) 我的也是，就1.2.1版本

你升级1.3 就好了

**Comment by duskdusts** [comment]
主要是个人懒得整了，考虑到这个是官网直接下载所得到的版本，也是很多人会用的版本，维护一下应该还是有一定必要的。

**Comment by duskdusts** [comment]
![图片](https://github.com/mrgeneralgoo/typecho-markdown/assets/60814886/f2b1d392-f712-460b-90ca-ed68c96e7c7e)
好像还是不行

**Comment by mrgeneralgoo** [comment]
@duskdusts  目前官网下载的版本都是 1.2.1 了，然后我用过往的 1.2 镜像跑了下，也没问题 🤔️

你这个 1.2 是从哪里下载的？

**Comment by duskdusts** [comment]
http://typecho.org/build.tar.gz

**Comment by mrgeneralgoo** [comment]
这个地址 404 了

**Comment by duskdusts** [comment]
好的，可能是我这边问题，我改天看看
