### ISSUE TITLE
使用>标签后位置不对

### ISSUE THREAD

**Issue by hxuf** [mrgeneralgoo/typecho-markdown#6]
跟EditorMD 实时显示的不一样。
![](https://img02.sogoucdn.com/app/a/100520146/4A45998C9190586DE020CF71FD2E845F)
![](https://img03.sogoucdn.com/app/a/100520146/B1305CAECDA2A5D6083A5F0792A37237)

**Comment by mrgeneralgoo** [comment]
@hxuf 好像没看出来位置的区别，似乎只是 css 样式的区别吧，EditorMD 自带了 css 样式，本插件并不附加任何样式渲染，主要是方便同自身博客风格上保持统一。

**Comment by hxuf** [comment]
>  这个标签。显示不一样。插件的显示不对称。

**Comment by hxuf** [comment]
`>` 标签

**Comment by mrgeneralgoo** [comment]
"CN2 方案如下：" 这段话层级好像不对，导致了缩进有区别。
