### ISSUE TITLE
字号标签能不能去除

### ISSUE THREAD

**Issue by hxuf** [mrgeneralgoo/typecho-markdown#9]
```
<h3 id="%E7%9F%AD%E7%BD%91%E5%9D%80%E7%94%9F%E6%88%90%E5%99%A8%EF%BC%9A">短网址生成器：</h3>
原生typecho的解析器就是直接 
<h3 >短网址生成器：</h3>
```

**Comment by mrgeneralgoo** [comment]
没太明白你的意思。

具体是什么问题？

**Comment by hxuf** [comment]
> 没太明白你的意思。
> 
> 具体是什么问题？

就是### 不是代表增大字么。 然后在这个插件里解析是<h 3 id="%E7%9F%AD%E7%BD%91%E5%9D%80%E7%94%9F%E6%88%90%E5%99%A8%EF%BC%9A">这样的。

希望能改成原版那种<h 3 > </h3> 这样的。

**Comment by hxuf** [comment]
我找到描述的方法了。其实我就是想禁用header id。

**Comment by mrgeneralgoo** [comment]
这个有什么负面影响吗？

**Comment by hxuf** [comment]
> 这个有什么负面影响吗？

这个倒是没有，只是我喜欢用这个标题标签。平时会很长。没有这个ID就好了。

**Comment by mrgeneralgoo** [comment]
谢谢反馈，已经更新了：如果没有识别到`[TOC]`语法的时候，原样输出。
